---
collections:
  - name: amazon.aws
#    source: https://pah.gregsowell.com
    
#  - name: amazon.cloud
#    source: https://pah.gregsowell.com
  
  - name: community.aws
#    source: https://pah.gregsowell.com
